supermarket/config/routes.rb
Supermarket::Application.routes.draw do
  

  resources :home
  resources :suppliers
  resources :categories

  root :to => 'home#index'

end

supermarket/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :suppliers
end

supermarket/app/models/supplier.rb
class Supplier < ActiveRecord::Base
   belongs_to :category

end

supermarket/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

supermarket/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
def index
  @category = Category.all
end
def new
  @category= Category.new
end
def create
  @category = Category.new(params[:category])
  
  if @category.save
    redirect_to suppliers_path
  else
  render :action => "new"
  end        

end
def edit
  @category = Category.find(params[:id])
end
def update
  @category = Category.find(params[:id])
    if @category.update_attributes(params[:category])
       redirect_to categories_path
    else
      render :action => "edit"
    end
end
def destroy
  @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
end
end

supermarket/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def show
    
  end
end

supermarket/app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  
def index
  @suppliers = Supplier.all
end

def new
  @supplier = Supplier.new
  
end
def create
  @supplier = Supplier.new(params[:supplier])
  
  if @supplier.save
    redirect_to suppliers_path
  else
  render :action => "new"
  end        

end
def show
  
  @supplier = Supplier.find(params[:id])
end
def edit
  @supplier = Supplier.find(params[:id])
end
def update
  @supplier = Supplier.find(params[:id])
    if @supplier.update_attributes(params[:supplier])
       redirect_to suppliers_path
    else
      render :action => "edit"
    end
end
def destroy
  @supplier = Supplier.find(params[:id])
    @supplier.destroy
    redirect_to suppliers_path
end
end

supermarket/app/helpers/application_helper.rb
module ApplicationHelper
end

supermarket/app/helpers/categories_helper.rb
module CategoriesHelper
end

supermarket/app/helpers/home_helper.rb
module HomeHelper
end

supermarket/app/helpers/suppliers_helper.rb
module SuppliersHelper
end

supermarket/app/views/categories/edit.html.erb
<h1>Ändra en kategori</h1>

<%= form_for @category do |f|%>
	<div class="text_field">
		<p>
		<%= f.label "Kategori" %>
		<%=f.text_field :categoryName%>
		</p>
		<p>
		<%= f.submit "Lägg till en kategori"%>
		</p>
	</div>
<%end%>

supermarket/app/views/categories/index.html.erb
	<div class="span9">
		<table class="table">
			<thead>
				<tr>
					<th>Kategorinamn</th>
					<th>Ändra</th>
					<th>Ta bort</th>
				</tr>
			</thead>
			<tbody>
					<% @category.each do |c|%> 
					<td><%= c.categoryName %></td>
					<td><%= link_to 'Ändra', :id => c.id, :controller => :categories, :action => "edit" %></td>
					<td><%= link_to 'X', c, :confirm => "Vill du radera denna kategori", :method => :delete, :class => "categories" %></td>
					
					</tr>
					
					<% end %>
					
					
					
			</tbody>
		</table>
	</div>

supermarket/app/views/categories/new.html.erb
<h1>Lägg till ett företag</h1>

<%= form_for @category do |f|%>
	<div class="text_field">
		<p>
		<%= f.label :categoryName %>
		<%=f.text_field :categoryName%>
		</p>
		<p>
		<%= f.submit "Lägg till en kategori"%>
		</p>
	</div>
<%end%>

supermarket/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

supermarket/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Mt222bmProject</title>
		<%= stylesheet_link_tag    "application" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<style type="text/css">
			body {
				padding-top: 60px;
			}
		</style>
	</head>
	  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">

        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Webb-Leverantör</a>
          <div class="nav-collapse">

            <ul class="nav">
              <li class=><a href="#">hem</a></li>
              <li><%= link_to("Företag", {:controller => "suppliers", :action => "index" }) %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>

      </div>
    </div>

    <div class="container">

     <%= yield %>
    </div> <!-- /container -->

   
  </body>
</html>

supermarket/app/views/suppliers/edit.html.erb
<h1>Lägg till ett företag</h1>

<%= form_for @supplier do |f|%>
	<div class="text_field">
		<p>
		<%= f.label :name %>
		<%=f.text_field :name%>
		</p>
		<p>
		<%= f.label :city %>
		<%=f.text_field :city %>
		</p>
				<p>
		<%= f.label :Contactperson %>
		<%=f.text_field :Contactperson %>
		</p>
				<p>
		<%= f.label :Phonenumber %>
		<%=f.text_field :Phonenumber %>
		</p>
		<p>
		<%= f.select :category_id, options_from_collection_for_select(Category.all, :id, :categoryName) %>
		</p>
		<p>
		<%= f.submit "Lägg till företag"%>
		</p>
	</div>
<%end%>

supermarket/app/views/suppliers/index.html.erb
<div class="row-fluid">
	<div class="span3">
		<div class="well sidebar-nav">
			<ul class="nav nav-list">
				<li class="nav-header">
					Altenativa menyval
				</li>
				<li>
					<%= link_to("Lägg till ett företag", {:controller => "suppliers", :action => "new" }) %>
				</li>
				<li>
					<%= link_to("Lägg till en kategori", {:controller => "categories", :action => "new" }) %>
				</li>
				<li>
					<%= link_to("Inställning för kategorier", {:controller => "categories", :action => "index" }) %>
				</li>
				
			</ul>
		</div><!--/.well -->
	</div>
	<div class="span9">
		<table class="table">
			<thead>
				<tr>
					<th>Företagsnamn</th>
					<th>Kategori</th>
					<th>Ändra</th>
					<th>Ta bort</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<% @suppliers.each do |s|%> 
					<td><%= link_to(s.name , supplier_path(s)) %></td>
					<td><%= s.category.try(:categoryName) %></td>
					<td><%= link_to 'Ändra', :id => s.id, :controller => :suppliers, :action => "edit" %></td>
					<td><%= link_to 'X', s, :confirm => "Vill du radera detta företag?", :method => :delete, :class => "suppliers" %></td>
					
					</tr>
					
					<% end %>
					
			</tbody>
		</table>
	</div>
</div>

supermarket/app/views/suppliers/new.html.erb
<h1>Lägg till ett företag</h1>

<%= form_for @supplier do |f|%>
	<div class="text_field">
		<p>
		<%= f.label :name %>
		<%=f.text_field :name%>
		</p>
		<p>
		<%= f.label :city %>
		<%=f.text_field :city %>
		</p>
				<p>
		<%= f.label :Contactperson %>
		<%=f.text_field :Contactperson %>
		</p>
				<p>
		<%= f.label :Phonenumber %>
		<%=f.text_field :Phonenumber %>
		</p>
		<p>
		<%= f.select :categories_id, options_from_collection_for_select(Category.all, :id, :categoryName) %>
		</p>
		<p>
		<%= f.submit "Lägg till företag"%>
		</p>
	</div>
<%end%>

supermarket/app/views/suppliers/show.html.erb
<div class="span9">
	<table class="table">
		<thead>
			<tr>
				<th>Namn</th>
				<th>Stad</th>
				<th>Kontaktperson</th>
				<th>Telefon</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><%= @supplier.name %></td>
				<td><%= @supplier.city %></td>
				<td><%= @supplier.Contactperson %></td>
				<td><%= @supplier.Phonenumber %></td>
			</tr>
		
		</tbody>
	</table>
<img src="http://maps.googleapis.com/maps/api/staticmap?center=<%= @supplier.city %>&zoom=14&amp;size=700x400&amp;sensor=false">
</div>